# Generated by Django 5.1.6 on 2025-02-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mod_msgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('if_user', models.BooleanField()),
                ('create_date', models.CharField(max_length=20)),
                ('msg', models.TextField()),
            ],
        ),
    ]
