# Generated by Django 5.1.6 on 2025-02-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_msgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('if_user', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='mod_msgs',
        ),
    ]
