# Generated by Django 5.1.6 on 2025-03-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_openaithread'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaithread',
            name='assistant_name',
            field=models.CharField(default='1', null=True),
        ),
    ]
