# Generated by Django 5.1.6 on 2025-02-15 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mod_contacts_user_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mod_contacts',
        ),
        migrations.DeleteModel(
            name='user_files',
        ),
    ]
