# Generated by Django 5.1.6 on 2025-03-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_openaithread_assistant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_msgs',
            name='assistant_name',
            field=models.CharField(default='0', null=True),
        ),
    ]
