# Generated by Django 5.1.6 on 2025-02-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp_mod_msgs',
        ),
        migrations.RemoveField(
            model_name='user_files',
            name='doc',
        ),
        migrations.AddField(
            model_name='user_files',
            name='doc_name',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_files',
            name='doc_url',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mod_msgs',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
