# Generated by Django 5.1.6 on 2025-02-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_temp_mod_msgs_remove_user_files_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_files',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
