# Generated by Django 5.1.6 on 2025-02-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_mod_contacts_user_files_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod_contacts',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mod_msgs',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='term_agree',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_files',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
