# Generated by Django 5.1.6 on 2025-02-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_mod_contacts_create_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod_contacts',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='mod_msgs',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='term_agree',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='user_files',
            name='create_date',
        ),
    ]
