# Generated by Django 5.1.6 on 2025-02-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_mod_contacts_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod_contacts',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mod_msgs',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='term_agree',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user_files',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
